env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - standard-with-typescript
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
plugins:
  - react
rules:
  ##### Possible Errors #####

  no-comma-dangle: 0         # disallow trailing commas in object literals
  no-cond-assign: 0          # disallow assignment in conditional expressions
  no-console: 0              # disallow use of console (off by default in the node environment)
  no-constant-condition: 0   # disallow use of constant expressions in conditions
  no-control-regex: 0        # disallow control characters in regular expressions
  no-debugger: 0             # disallow use of debugger
  no-dupe-keys: 0            # disallow duplicate keys when creating object literals
  no-empty: 0                # disallow empty statements
  no-empty-class: 0          # disallow the use of empty character classes in regular expressions
  no-ex-assign: 0            # disallow assigning to the exception in a catch block
  no-extra-boolean-cast: 0   # disallow double-negation boolean casts in a boolean context
  no-extra-parens: 0         # disallow unnecessary parentheses (off by default)
  no-extra-semi: 0           # disallow unnecessary semicolons
  no-func-assign: 0          # disallow overwriting functions written as function declarations
  no-inner-declarations: 0   # disallow function or variable declarations in nested blocks
  no-invalid-regexp: 0       # disallow invalid regular expression strings in the RegExp constructor
  no-irregular-whitespace: 0 # disallow irregular whitespace outside of strings and comments
  no-negated-in-lhs: 0       # disallow negation of the left operand of an in expression
  no-obj-calls: 0            # disallow the use of object properties of the global object (Math and JSON) as functions
  no-regex-spaces: 0         # disallow multiple spaces in a regular expression literal
  no-reserved-keys: 0        # disallow reserved words being used as object literal keys (off by default)
  no-sparse-arrays: 0        # disallow sparse arrays
  no-unreachable: 0          # disallow unreachable statements after a return throw continue or break statement
  use-isnan: 0               # disallow comparisons with the value NaN
  valid-jsdoc: 0             # Ensure JSDoc comments are valid (off by default)
  valid-typeof: 0            # Ensure that the results of typeof are compared against a valid string
  semi: 0
